### ISSUE TITLE
Make more clear what the semantics of the `a` and `b` parameters for `is_compatible` are

### ISSUE THREAD

**Issue by sschuberth** [priv-kweihmann/osadl-matrix#1]
See

https://github.com/priv-kweihmann/osadl-matrix/blob/def8436c2c882bd085b51f070e32f4d84b2068a8/osadl_matrix/__init__.py#L38-L43

as `is_compatible(a, b)` is not (necessarily) the same as `is_compatible(b, a)`, how about making that more clear by renaming the parameters to something like `outbound` and `inbound` (plus adding docs for these parameters what this actually means)?

**Comment by priv-kweihmann** [comment]
Feel free to add some documentation - PRs are welcome.
As of now the library is awaiting major changes anyway, so that interface will likely change as well.

**Comment by sschuberth** [comment]
So, is it worth to submit a PR then? Do you agree with the proposed names?

And out of curiosity, what kind of major changes are coming? I mean, it seems there's not much you could do different for such a simple interface 😀

**Comment by priv-kweihmann** [comment]
To provide a little background, OSADL decided to take down the public database (this library is based on) and a new accessible one is still in the making.
Additionally we will add more/different interface to the library (more than the few ones available) now.
So with this in mind I personally would consider the library in some kind of beta stage at the moment.

> So, is it worth to submit a PR then? Do you agree with the proposed names?
PRs are fine, the suggested wording as well :wink:
