### ISSUE TITLE
Undef becomes False

### ISSUE THREAD

**Issue by hesa** [priv-kweihmann/osadl-matrix#21]
The method `from_text` as defined in the class `OSADLCompatibility`:
```
class OSADLCompatibility(Enum):
    YES = True
    NO = False
    UNDEF = False

    @staticmethod
    def from_text(_in):
        if _in == 'Yes':
            return OSADLCompatibility.YES
        if _in == 'No':
            return OSADLCompatibility.NO
        return OSADLCompatibility.UNDEF
```
will return "No" in all cases but if the input parameter is "Yes". 

_Note how both `NO` and `UNDEF` are defined to be `False`._

On one hand this is fine, in not being True, but the undefined compatibility of for example `MPL-2.0` and `AFL-2.0` is "hidden" as a "No".

I would prefer using the undefined (i.e. "?" in the matrix from OSADL) being propagated to the caller, thus returning (for now) correspondingly Yes, No, Undefined.

***Example code***:

```
print(str(osadl_matrix.OSADLCompatibility.YES))
print(str(osadl_matrix.OSADLCompatibility.NO))
print(str(osadl_matrix.OSADLCompatibility.UNDEF))
```
will output
```
OSADLCompatibility.YES
OSADLCompatibility.NO
OSADLCompatibility.NO
```

```

**Comment by priv-kweihmann** [comment]
I think it's just a matter of the string representation - personally I would prefer to return boolean, but it's fair for potential users to replace pattern like

```
if is_compatible('a', 'b'):
```

by

```
if is_compatible('a', 'b') == OSADLCompatibility.YES:
```

so feel free to replace the boolean values behind this enum by strings of your choice

**Comment by hesa** [comment]
This is what the issue is all about, should it be:
* "Yes" => True
* all other, including future strings, returns False
... or should the OSADL matrix different values be propagated?

But with the current code, I think having the third value in the Enum is misleading. I would expect to return three different values. And YES, I do see that there are boolean values in the Enum and I should have concluded way faster than I did yesterday that `NO` and `UNDEF` are the same. 

This test assumes, or at least conveys (to me at least) the message, that `UNDEF` is used
`        assert osadl_matrix.is_compatible("My-Fairy-Little-License", "LGPL-2.1-only") == osadl_matrix.OSADLCompatibility.UNDEF
`
The test above does not fail since `UNDEF` and `NO` are the same.

**Comment by hesa** [comment]
Having a boolean return value might be enough (certainly easier to program against as you mentioned). I would guess I am mainly interested in quickly finding out if A and B are compatible without any doubts. 

I will think about this for a while...

**Comment by priv-kweihmann** [comment]
@hesa can we close this one here after #22 is merged?

**Comment by hesa** [comment]
Yes, please
