### ISSUE TITLE
Proposal to add a timestamp check to protect users from working with outdated material

### ISSUE THREAD

**Issue by osadl** [priv-kweihmann/osadl-matrix#29]
In principle, nothing can be said against someone copying data available under an Open Source license from a publicly accessible server and distributing the material from their Github account. And they can then also write own software that provides the same functionality that is already available on the original server. Why not do something superfluous for a change?

However, this project is an actively developed project that deals with legally relevant data. They may well change over time, e.g. because bugs are removed or because legal opinions are adapted. Therefore, one might well see a certain deficit of responsibility if, firstly, outdated data sets are kept in the repository and, secondly - much more seriously - if the user of the provided software unknowingly accesses a local copy of the data that is never necessarily updated.

To make matters worse, a timestamp variable is maintained on the primary data server, and the associated web pages tirelessly and imploringly ask that local copies only be used if the timestamp has been previously checked and ensured that the data are up to date.

Of course, the simplest solution would be to simply remove the "osadl-matrix" repository. But if there is an urgent desire to keep this repository for whatever reason, then at least a timestamp check should be added to the software.

Proposal
```
Index: osadl-matrix/osadl_matrix/__init__.py
===================================================================
--- osadl-matrix.orig/osadl_matrix/__init__.py
+++ osadl-matrix/osadl_matrix/__init__.py
@@ -4,10 +4,18 @@
 
 import csv
 import os
+import time
+import datetime
+from urllib.request import urlopen
+from os.path import expanduser
 from enum import Enum, unique
 
+OSADL_MATRIX_TIMESTAMP_URL = 'https://www.osadl.org/fileadmin/checklists/timestamp'
+OSADL_MATRIX_TIMESTAMP_FORMAT_URL = 'https://www.osadl.org/fileadmin/checklists/timeformat'
+OSADL_MATRIX_URL = 'https://www.osadl.org/fileadmin/checklists/matrix.csv'
 OSADL_MATRIX = os.path.join(os.path.dirname(__file__), 'osadl-matrix.csv')
-OSADL_MATRIX_JSON = os.path.join(os.path.dirname(__file__), 'osadl-matrix.json')
+OSADL_MATRIX_USER = os.path.join(expanduser("~"), 'osadl-matrix.csv')
+
 __osadl_db = {}
 
 
@@ -46,7 +54,23 @@ def __read_db(customdb=None):
     """
     global __osadl_db
     if not __osadl_db:
-        with open(customdb or OSADL_MATRIX) as i:
+        timestamp = urlopen(OSADL_MATRIX_TIMESTAMP_URL).read().decode("utf-8")
+        timestampformat = urlopen(OSADL_MATRIX_TIMESTAMP_FORMAT_URL).read().decode("utf-8")
+        timestamptime = time.mktime(datetime.datetime.strptime(timestamp, timestampformat).timetuple())
+
+        if os.path.isfile(OSADL_MATRIX_USER):
+            OSADL_MATRIX_IN_USE = OSADL_MATRIX_USER
+        else:
+            OSADL_MATRIX_IN_USE = OSADL_MATRIX
+        localmatrixmtime = os.path.getmtime(OSADL_MATRIX_IN_USE)
+
+        if timestamptime > localmatrixmtime:
+            newmatrix = urlopen(OSADL_MATRIX_URL).read().decode("utf-8")
+            localmatrix = open(OSADL_MATRIX_USER, 'w')
+            localmatrix.write(newmatrix)
+            localmatrix.close()
+            OSADL_MATRIX_IN_USE = OSADL_MATRIX_USER
+        with open(customdb or OSADL_MATRIX_IN_USE) as i:
             _reader = csv.DictReader(i, delimiter=',', quotechar='"')
             for row in _reader:
                 key = row['Compatibility*']

```

**Comment by priv-kweihmann** [comment]
I see the point but the proposal feels wrong in various ways.

- the library is designed to provide data even in an environment where upstream server cannot be reached (corporate networks, etc.), so every mandatory "online ping" functionality will inevitable break use cases for existing users, and therefore cannot be considered
- this library does as well test extensively the data for sanity before a release, so every release guarantees that for the same input the same output can be expected, which would not be the case if we all of sudden exchange the data on the fly (and without any notification) - this would be a very bad design pattern
- the library is updated frequently so (if users take a reasonable amount of care about their installation) there's little to zero change to have very outdated data being provided by the lib's defaults
- all the provided library functions allow passing a `custom` db, so users that want to use their own or a different (potentially) more recent version of data are free to do so. As this library has no standalone functionality and has to be embedded into a larger application framework, I find this trade-off acceptable
- the timestamp of the data can be already implicitly gathered from the version of the release (all release version are just timestamps, when the data was gathered and packed up)
- additional remark: the above code lacks any kind of error handling, like connectivity issue, broken data transmission.
  also I dislike that the user's home directory is brought into the mix, as it will simply not work with throw-away containers or containers that for whatever reason are running the library code as root
- this project is not responsible for the downstream dependency update hygiene and we cannot enforce any updates on downstream users - all that can be done is to encourage to always use the latest release, but nothing more
  
If a more detailed information is needed when the data was created upstream, I would expect it to be part of data file that one can download - once that would be available the needed functionality can be added here.
I personally consider an additional "timestamp" file as insufficient, as from my perspective there's no correlation between the one file and the other, meaning the one file can change without the other being changed

**Comment by osadl** [comment]
If there is ever a contest for the most arrogant maintainer of all time, I'll be sure to give you my vote.

#1 rule to get there: If you don't have a single relevant argument, collect as many irrelevant arguments as possible and impress the other with the shear number.

You say: "All that can be done is to encourage to always use the latest release, but nothing more", but you fail to do so. You even fail to follow this encouragement yourself: One of the contributors of your software detected a critical problem in our compatibility matrix more than a week ago. We immediately discussed this with our lawyer and after less than 24 hours the problem was fixed, corrected on the web and the timestamp was updated. This morning, more than a week later, I pulled your repository and updated my local installation. Guess what I found: Yes, you are still distributing the old incorrect data.
