### ISSUE TITLE
Hint about what the new "Check dependency" means

### ISSUE THREAD

**Issue by sschuberth** [priv-kweihmann/osadl-matrix#4]
Is there any hint about what the [newly introduced](https://github.com/priv-kweihmann/osadl-matrix/commit/fca2b4b1deca6cf8b21968f175dedec7681343a3) "Check dependency" value means? Check in what way? Linkage type (static vs dynamic)?

**Comment by priv-kweihmann** [comment]
You should point this question to osadl office and not to this project
